'use strict';
const {run,runWithInput}=require('../../core/runtime');
function parseSslHelperError(error){const raw=String(error?.message||'SSL gagal.');const marker='HOSTPANEL_SSL_ERROR:';const i=raw.indexOf(marker);if(i<0)return{type:'generic',message:raw};try{const p=JSON.parse(raw.slice(i+marker.length).trim());return p&&typeof p==='object'?p:{type:'generic',message:raw};}catch{return{type:'generic',message:raw};}}
function normalizeRetryAfter(value){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();}
function rateLimitMessage(info){const retry=normalizeRetryAfter(info.retryAfter);const registered=info.registeredDomain?` untuk registered domain ${info.registeredDomain}`:'';return `Let's Encrypt sedang terkena rate limit${registered}. Ini bukan kegagalan DNS/Nginx. ${retry?`Jangan retry production sebelum ${retry}. `:''}Gunakan Tes Staging untuk pengujian sementara.`;}
function settingsFromDomain(d,overrides={}){let headers={};try{headers=JSON.parse(d.custom_headers_json||'{}');}catch{}return{hostname:d.hostname,port:d.target_port,redirectHttps:overrides.redirectHttps??Boolean(d.redirect_https),canonicalMode:overrides.canonicalMode??d.canonical_mode??'none',websocketEnabled:overrides.websocketEnabled??Boolean(d.websocket_enabled),uploadLimitMb:overrides.uploadLimitMb??d.upload_limit_mb??25,proxyTimeoutSec:overrides.proxyTimeoutSec??d.proxy_timeout_sec??60,maintenanceMode:overrides.maintenanceMode??Boolean(d.maintenance_mode),customHeaders:overrides.customHeaders??headers};}
async function proxy(hostname,port){const out=await run('nginx-proxy-upsert',[hostname,port]);try{return JSON.parse(String(out.stdout||'').trim().split('\n').pop());}catch{return{https:false};}}
async function proxyAdvanced(domain,overrides={}){const payload=settingsFromDomain(domain,overrides);const out=await runWithInput('nginx-proxy-upsert-json',JSON.stringify(payload),{timeout:30000});try{return JSON.parse(String(out.stdout||'').trim().split('\n').pop());}catch{return{https:false};}}
function parseHeaders(raw){const text=String(raw||'').trim();if(!text)return{};let obj;try{obj=JSON.parse(text);}catch{throw new Error('Custom headers harus berupa JSON object yang valid.');}if(!obj||typeof obj!=='object'||Array.isArray(obj))throw new Error('Custom headers harus berupa JSON object.');return obj;}
function domainSettings(body){const canonicalMode=String(body.canonical_mode||'none');if(!['none','www','non-www'].includes(canonicalMode))throw new Error('Canonical mode tidak valid.');const uploadLimitMb=Number(body.upload_limit_mb||25),proxyTimeoutSec=Number(body.proxy_timeout_sec||60);if(!Number.isInteger(uploadLimitMb)||uploadLimitMb<1||uploadLimitMb>2048)throw new Error('Upload limit harus 1-2048 MB.');if(!Number.isInteger(proxyTimeoutSec)||proxyTimeoutSec<5||proxyTimeoutSec>3600)throw new Error('Proxy timeout harus 5-3600 detik.');return{redirectHttps:body.redirect_https==='1',canonicalMode,websocketEnabled:body.websocket_enabled==='1',uploadLimitMb,proxyTimeoutSec,maintenanceMode:body.maintenance_mode==='1',customHeaders:parseHeaders(body.custom_headers_json)};}
module.exports={run,parseSslHelperError,normalizeRetryAfter,rateLimitMessage,proxy,proxyAdvanced,domainSettings,settingsFromDomain};
