'use strict';
const fs=require('node:fs');const assert=require('node:assert');
const read=(p)=>fs.readFileSync(p,'utf8');
const mid=read('src/modules/billing/midtrans.service.js');
assert(mid.includes("createHash('sha512')"),'Midtrans SHA512 signature verification missing');
assert(mid.includes('/v2/${encodeURIComponent(orderId)}/status'),'Midtrans GET status reconciliation missing');
assert(mid.includes('/v1/subscriptions'),'Midtrans recurring Subscription API missing');
assert(read('src/app.js').includes("/hooks/midtrans"),'Midtrans webhook route not mounted');
const gh=read('src/modules/integrations/integrations.service.js');
assert(gh.includes('app/installations'),'GitHub App installation API missing');
assert(gh.includes('installation/repositories'),'GitHub App repository listing missing');
assert(gh.includes('login/oauth/authorize'),'GitHub OAuth flow missing');
const appSvc=read('src/modules/apps/apps.service.js');
assert(appSvc.includes('await integrations.repoToken(workspaceId)'),'Private GitHub App deploy token fallback missing');
const id=JSON.parse(read('src/locales/id.json'));const en=JSON.parse(read('src/locales/en.json'));
assert.deepStrictEqual(Object.keys(id).sort(),Object.keys(en).sort(),'i18n catalogs have different key sets');
const nr=read('src/modules/notifications/notifications.routes.js');
for(const route of ['/delete-read','/delete-all','/delete-selected',"/:id/delete"])assert(nr.includes(route),`notification action missing: ${route}`);
console.log('integrations-basics: ok');
