'use strict';const crypto=require('node:crypto');const model=require('./previews.model');const apps=require('../apps/apps.service');const environments=require('../environments/environments.service');const {run,runWithInput}=require('../../core/runtime');const validators=require('../../lib/validators');const extra=require('../../core/security/validators');const integrations=require('../integrations/integrations.service');
function branch(raw){return extra.gitBranch(raw||'main');}
function previewSlug(appSlug,branchName){const stem=String(branchName).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,14)||'preview';const hash=crypto.createHash('sha256').update(branchName).digest('hex').slice(0,7);return `${String(appSlug).slice(0,16)}-${stem}-${hash}`.slice(0,40).replace(/-+$/,'');}
function envText(map){return Object.entries(map||{}).map(([k,v])=>`${k}="${String(v).replace(/\\/g,'\\\\').replace(/"/g,'\\"')}"`).join('\n')+(Object.keys(map||{}).length?'\n':'');}
function hostname(app,b){if(!app.preview_domain_suffix)return'';const stem=String(b).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,24)||'preview';return validators.domain(`${stem}-${app.slug}.${app.preview_domain_suffix}`);}
async function create(workspaceId,userId,appId,rawBranch,ttlDays=7){const app=model.app(appId,workspaceId);if(!app)throw new Error('Project tidak ditemukan.');if(!app.preview_enabled)throw new Error('Preview environments belum diaktifkan pada project.');if(!app.git_repo)throw new Error('Preview memerlukan Git repository.');const b=branch(rawBranch);const existing=model.byAppBranch(app.id,b);if(existing&&existing.status!=='stopped')throw new Error('Preview branch ini sudah ada. Hapus/stop preview lama terlebih dahulu.');const port=model.nextPort(),slug=previewSlug(app.slug,b),host=hostname(app,b),id=model.create({workspaceId,appId:app.id,branch:b,slug,hostname:host,port,ttlDays:Math.max(1,Math.min(Number(ttlDays)||7,30)),userId});try{const env=environments.materialize(app.id,'preview');const payload={previewSlug:slug,appSlug:app.slug,workingDir:app.working_dir,gitRepo:app.git_repo,branch:b,gitToken:apps.gitToken(app.id)||await integrations.repoToken(workspaceId),port,buildScript:app.build_script||'',installCommand:app.install_command||'npm ci',nodeRuntime:app.node_runtime||'system',startMode:app.start_mode||'npm',entryFile:app.entry_file||'server.js',npmScript:app.npm_script||'start',startCommand:app.start_command||'',restartPolicy:app.restart_policy||'on-failure',healthPath:app.health_path||'/',memoryLimitMb:Math.min(Number(app.memory_limit_mb)||512,2048),environmentText:envText(env)};const result=JSON.parse(String((await runWithInput('preview-deploy-json',JSON.stringify(payload),{timeout:900000,maxBuffer:2*1024*1024})).stdout||'{}').trim().split('\n').pop());if(host){await run('nginx-proxy-upsert',[host,port],{timeout:30000});}model.active(id,result);return model.find(id,workspaceId);}catch(error){model.failed(id);try{await run('preview-remove',[slug,app.working_dir],{timeout:60000});}catch{}throw error;}}
async function remove(preview){if(preview.hostname){try{await run('nginx-remove',[preview.hostname],{timeout:30000});}catch{}}await run('preview-remove',[preview.slug,preview.working_dir],{timeout:60000});model.stopped(preview.id);}
async function logs(preview){return String((await run('preview-logs',[preview.slug,250],{timeout:20000})).stdout||'');}
async function cleanupExpired(){for(const item of model.expired(5)){try{await remove(item);}catch{}}}
module.exports={list:model.list,find:model.find,create,remove,logs,cleanupExpired};
