'use strict';
const v=require('../../lib/validators');const extra=require('../../core/security/validators');const {run,runWithInput}=require('../../core/runtime');const config=require('../../core/config');const model=require('./apps.model');const vault=require('../../core/security/vault');const integrations=require('../integrations/integrations.service');
function bool(v){return ['1','true','on','yes'].includes(String(v||'').toLowerCase());}
function payload(body,fixedSlug=null){const name=String(body.name||'').trim().slice(0,80);if(!name)throw new Error('Nama aplikasi wajib diisi.');const slug=fixedSlug||v.slug(body.slug);const workingDir=v.workingDir(body.working_dir);const port=v.port(body.port);const startMode=['node','npm','command'].includes(String(body.start_mode||'node'))?String(body.start_mode||'node'):'node';const entryFile=v.entryFile(body.entry_file||'server.js');const npmScript=extra.npmScript(body.npm_script||'start')||'start';const startCommand=String(body.start_command||'').trim().slice(0,500);const environmentText=String(body.environment_text||'').slice(0,64*1024);const environmentAction=body.environment_action==='preserve'?'preserve':'replace';const restartPolicy=['always','on-failure','no'].includes(String(body.restart_policy||'on-failure'))?String(body.restart_policy||'on-failure'):'on-failure';const gitRepo=extra.gitRepo(body.git_repo);const gitBranch=extra.gitBranch(body.git_branch||'main');const buildScript=extra.npmScript(body.build_script);const healthPath=extra.healthPath(body.health_path||'/');const memoryLimitMb=extra.optionalInteger(body.memory_limit_mb,0,65536,'Memory limit');const cpuQuotaPercent=extra.optionalInteger(body.cpu_quota_percent,0,800,'CPU quota');const tasksMax=extra.optionalInteger(body.tasks_max,0,4096,'Tasks max');const nodeRuntime=extra.nodeRuntime(body.node_runtime||'system');const installCommand=extra.installCommand(body.install_command||'npm ci');const releaseKeep=extra.optionalInteger(body.release_keep||5,2,20,'Release retention')||5;const previewDomainSuffix=body.preview_domain_suffix?extra.domainSuffix(body.preview_domain_suffix):'';const template=['existing','express','node-worker','static'].includes(String(body.template||'existing'))?String(body.template||'existing'):'existing';return{name,slug,workingDir,port,startMode,entryFile,npmScript,startCommand,environmentText,environmentAction,restartPolicy,gitRepo,gitBranch,buildScript,healthPath,memoryLimitMb,cpuQuotaPercent,tasksMax,nodeRuntime,deployStrategy:'atomic',autoDeploy:bool(body.auto_deploy),previewEnabled:bool(body.preview_enabled),previewDomainSuffix,installCommand,releaseKeep,template};}
function assertQuota(workspaceId){const ws=model.workspace(workspaceId);if(ws?.max_apps>0&&model.count(workspaceId)>=ws.max_apps)throw new Error(`Quota workspace tercapai: maksimal ${ws.max_apps} project.`);}
async function statuses(){try{const out=JSON.parse((await run('app-status-all',[],{timeout:20000})).stdout||'[]');return new Map((Array.isArray(out)?out:[]).map((x)=>[x.slug,x]));}catch{return new Map();}}
async function metrics(){try{const out=JSON.parse((await run('app-metrics-all',[],{timeout:20000})).stdout||'[]');return new Map((Array.isArray(out)?out:[]).map((x)=>[x.slug,x]));}catch{return new Map();}}
async function upsertRuntime(p){await runWithInput('app-upsert-json',JSON.stringify(p),{timeout:30000});}
async function proxyUpsert(hostname,port){const result=await run('nginx-proxy-upsert',[hostname,port]);try{return JSON.parse(String(result.stdout||'').trim().split('\n').pop());}catch{return{https:false};}}
async function health(app){try{const data=JSON.parse((await run('app-health',[app.port,app.health_path||'/'],{timeout:10000})).stdout||'{}');try{model.markHealth(app.id,Boolean(data.ok),data.latencyMs);}catch{}return data;}catch(error){try{model.markHealth(app.id,false,0);}catch{}return{ok:false,error:error.message};}}
function credentialToken(appId){const c=model.gitCredential(appId);if(!c?.token_enc)return'';return vault.decrypt(c.token_enc);}
function setGitCredential(appId,token){const value=String(token||'').trim();if(!value)return;extra.gitToken(value);model.setGitCredential(appId,vault.encrypt(value));}
function clearGitCredential(appId){model.clearGitCredential(appId);}
async function deploy(app,{workspaceId,actorUserId=null,trigger='manual',environment='production'}={}){if(!app.git_repo)throw new Error('Repository Git belum dikonfigurasi untuk aplikasi ini.');const deploymentId=model.recordDeployment(app.id,workspaceId,'git',{actorUserId,trigger,environment});try{const payload={slug:app.slug,workingDir:app.working_dir,port:app.port,startMode:app.start_mode||'node',entryFile:app.entry_file||'server.js',npmScript:app.npm_script||'start',startCommand:app.start_command||'',restartPolicy:app.restart_policy||'on-failure',memoryLimitMb:app.memory_limit_mb||0,cpuQuotaPercent:app.cpu_quota_percent||0,tasksMax:app.tasks_max||0,nodeRuntime:app.node_runtime||'system',healthPath:app.health_path||'/',gitRepo:app.git_repo,gitBranch:app.git_branch||'main',buildScript:app.build_script||'',installCommand:app.install_command||'npm ci',releaseKeep:app.release_keep||5,environment,gitToken:credentialToken(app.id)||await integrations.repoToken(workspaceId)};const result=await runWithInput('app-deploy-json',JSON.stringify(payload),{timeout:900000,maxBuffer:2*1024*1024});let data={};try{data=JSON.parse(String(result.stdout||'').trim().split('\n').pop());}catch{data={message:result.stdout};}model.finishDeployment(deploymentId,'success',data);model.markDeployed(app.id,data.commit||null);if(data.releaseId)model.addRelease(app.id,deploymentId,{...data,environment,status:'active'});return data;}catch(error){model.finishDeployment(deploymentId,'failed',{branch:app.git_branch,message:error.message,logExcerpt:String(error.message||'').slice(0,8000)});throw error;}}
async function createTemplate(p){if(!p||p.template==='existing')return null;return runWithInput('app-template-create-json',JSON.stringify({slug:p.slug,workingDir:p.workingDir,template:p.template,port:p.port}),{timeout:30000});}
async function rollback(app,releaseId){const result=await run('app-release-activate',[app.slug,app.working_dir,releaseId],{timeout:60000});return JSON.parse(String(result.stdout||'{}').trim().split('\n').pop());}
async function serviceAction(serviceName,action){return run('service-action',[action,serviceName]);}
async function logs(slug,limit=200){return(await run('app-logs',[slug,limit],{timeout:20000})).stdout||'(belum ada log)';}
async function removeProxy(hostname){return run('nginx-remove',[hostname]);}async function removeRuntime(slug){return run('app-remove',[slug]);}
async function destroy(app,workspaceId){for(const d of model.domains(app.id,workspaceId))await removeProxy(d.hostname);await removeRuntime(app.slug);model.removeApp(app.id,workspaceId);}
async function rollbackCreate({hostname,appId,serviceMade,slug,workspaceId}){if(hostname){try{await removeProxy(hostname);}catch{}}if(appId){try{model.removeApp(appId,workspaceId);}catch{}}if(serviceMade&&slug){try{await removeRuntime(slug);}catch{}}}
async function githubRepos(workspaceId){return integrations.listRepos(workspaceId);}
async function inspectGithub(workspaceId,repo,branch){return integrations.inspectRepo(workspaceId,repo,branch);}
module.exports={payload,assertQuota,createTemplate,statuses,metrics,upsertRuntime,proxyUpsert,health,setGitCredential,clearGitCredential,deploy,rollback,serviceAction,logs,removeProxy,removeRuntime,destroy,rollbackCreate,githubRepos,inspectGithub,gitToken:credentialToken,config};
