'use strict';
const db=require('../../core/database');
function list(workspaceId){return db.prepare(`SELECT a.*, (SELECT d.hostname FROM domains d WHERE d.app_id=a.id ORDER BY d.id LIMIT 1) AS domain, COALESCE((SELECT d.ssl_enabled FROM domains d WHERE d.app_id=a.id ORDER BY d.id LIMIT 1),0) AS ssl_enabled FROM apps a WHERE a.workspace_id=? ORDER BY a.id DESC`).all(workspaceId);}
function count(workspaceId){return db.prepare('SELECT COUNT(*) AS n FROM apps WHERE workspace_id=?').get(workspaceId).n;}
function find(id,workspaceId){return db.prepare('SELECT * FROM apps WHERE id=? AND workspace_id=?').get(id,workspaceId);}
function findBySlug(slug){return db.prepare('SELECT * FROM apps WHERE slug=?').get(slug);}
function nextPort(){const used=new Set(db.prepare('SELECT port FROM apps UNION SELECT port FROM preview_deployments').all().map(r=>Number(r.port)));for(let port=4100;port<=9999;port++)if(!used.has(port))return port;throw new Error('Tidak ada port aplikasi tersedia pada range 4100-9999.');}
function findConflict(slug,port,excludeId=null){if(excludeId)return db.prepare('SELECT 1 FROM apps WHERE (slug=? OR port=?) AND id<>?').get(slug,port,excludeId);return db.prepare('SELECT 1 FROM apps WHERE slug=? OR port=?').get(slug,port);}
function create(p,workspaceId){return db.prepare(`INSERT INTO apps (workspace_id,name,slug,working_dir,entry_file,port,service_name,start_mode,start_command,npm_script,restart_policy,git_repo,git_branch,build_script,health_path,memory_limit_mb,cpu_quota_percent,tasks_max,node_runtime,deploy_strategy,auto_deploy,preview_enabled,preview_domain_suffix,install_command,release_keep,template) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(workspaceId,p.name,p.slug,p.workingDir,p.entryFile,p.port,`hostapp-${p.slug}`,p.startMode,p.startCommand,p.npmScript,p.restartPolicy,p.gitRepo||null,p.gitBranch,p.buildScript||null,p.healthPath,p.memoryLimitMb||0,p.cpuQuotaPercent||0,p.tasksMax||0,p.nodeRuntime||'system',p.deployStrategy||'atomic',p.autoDeploy?1:0,p.previewEnabled?1:0,p.previewDomainSuffix||null,p.installCommand||'npm ci',p.releaseKeep||5,p.template||'existing');}
function update(id,workspaceId,p){return db.prepare(`UPDATE apps SET name=?,working_dir=?,entry_file=?,port=?,start_mode=?,start_command=?,npm_script=?,restart_policy=?,git_repo=?,git_branch=?,build_script=?,health_path=?,memory_limit_mb=?,cpu_quota_percent=?,tasks_max=?,node_runtime=?,deploy_strategy=?,auto_deploy=?,preview_enabled=?,preview_domain_suffix=?,install_command=?,release_keep=?,template=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?`).run(p.name,p.workingDir,p.entryFile,p.port,p.startMode,p.startCommand,p.npmScript,p.restartPolicy,p.gitRepo||null,p.gitBranch,p.buildScript||null,p.healthPath,p.memoryLimitMb||0,p.cpuQuotaPercent||0,p.tasksMax||0,p.nodeRuntime||'system',p.deployStrategy||'atomic',p.autoDeploy?1:0,p.previewEnabled?1:0,p.previewDomainSuffix||null,p.installCommand||'npm ci',p.releaseKeep||5,p.template||'existing',id,workspaceId);}
function domains(appId,workspaceId){return db.prepare('SELECT * FROM domains WHERE app_id=? AND workspace_id=?').all(appId,workspaceId);}
function insertDomain(hostname,port,appId,tlsMode,workspaceId){return db.prepare(`INSERT INTO domains (workspace_id,hostname,target_port,app_id,nginx_enabled,tls_mode) VALUES (?,?,?,?,0,?)`).run(workspaceId,hostname,port,appId,tlsMode);}
function updateDomainPort(id,port,ssl,workspaceId){db.prepare('UPDATE domains SET target_port=?,ssl_enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?').run(port,ssl,id,workspaceId);}
function markDomain(hostname,ssl,workspaceId){db.prepare('UPDATE domains SET nginx_enabled=1,ssl_enabled=?,updated_at=CURRENT_TIMESTAMP WHERE hostname=? AND workspace_id=?').run(ssl,hostname,workspaceId);}
function removeApp(id,workspaceId){db.transaction(()=>{db.prepare('DELETE FROM domains WHERE app_id=? AND workspace_id=?').run(id,workspaceId);db.prepare('DELETE FROM apps WHERE id=? AND workspace_id=?').run(id,workspaceId);})();}
function recordDeployment(appId,workspaceId,source='git',extra={}){return Number(db.prepare(`INSERT INTO deployments (app_id,workspace_id,source,status,environment,trigger,actor_user_id) VALUES (?,?,?,'running',?,?,?)`).run(appId,workspaceId,source,extra.environment||'production',extra.trigger||'manual',extra.actorUserId||null).lastInsertRowid);}
function finishDeployment(id,status,data={}){db.prepare(`UPDATE deployments SET status=?,commit_sha=?,branch=?,message=?,release_id=?,previous_release_id=?,log_excerpt=?,finished_at=CURRENT_TIMESTAMP WHERE id=?`).run(status,data.commit||null,data.branch||null,String(data.message||'').slice(0,2000),data.releaseId||null,data.previousReleaseId||null,String(data.logExcerpt||'').slice(0,8000),id);}
function markDeployed(appId,commit){db.prepare('UPDATE apps SET last_deployed_commit=?,last_deployed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(commit||null,appId);}
function addRelease(appId,deploymentId,data){db.prepare(`INSERT OR REPLACE INTO releases (app_id,deployment_id,environment,release_id,path,commit_sha,status,node_runtime,lockfile_hash,artifact_sha256,build_duration_ms,activated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(appId,deploymentId,data.environment||'production',data.releaseId,data.path||'',data.commit||null,data.status||'active',data.nodeRuntime||null,data.lockfileHash||null,data.artifactSha256||null,Number(data.buildDurationMs)||null);}
function releases(appId,limit=20){return db.prepare('SELECT * FROM releases WHERE app_id=? ORDER BY id DESC LIMIT ?').all(appId,limit);}
function gitCredential(appId){return db.prepare('SELECT * FROM git_credentials WHERE app_id=?').get(appId);}
function setGitCredential(appId,tokenEnc,username='x-access-token'){db.prepare(`INSERT INTO git_credentials (app_id,username,token_enc) VALUES (?,?,?) ON CONFLICT(app_id) DO UPDATE SET username=excluded.username,token_enc=excluded.token_enc,updated_at=CURRENT_TIMESTAMP`).run(appId,username,tokenEnc);}
function clearGitCredential(appId){db.prepare('DELETE FROM git_credentials WHERE app_id=?').run(appId);}
function workspace(workspaceId){return db.prepare('SELECT * FROM workspaces WHERE id=?').get(workspaceId);}
function markHealth(id,ok,latency){db.prepare('UPDATE apps SET last_health_at=CURRENT_TIMESTAMP,last_health_ok=?,last_health_latency_ms=? WHERE id=?').run(ok?1:0,Number(latency||0),id);}
module.exports={list,count,find,findBySlug,nextPort,findConflict,create,update,domains,insertDomain,updateDomainPort,markDomain,removeApp,recordDeployment,finishDeployment,markDeployed,addRelease,releases,gitCredential,setGitCredential,clearGitCredential,workspace,markHealth};
