'use strict';
const db=require('../database');
const jobs=require('../jobs');
const runtime=require('../runtime');
const appModel=require('../../modules/apps/apps.model');
const appService=require('../../modules/apps/apps.service');
const previews=require('../../modules/previews/previews.service');
const alerts=require('../../modules/alerts/alerts.service');
const notifications=require('../../modules/notifications/notifications.service');
let jobBusy=false,healthBusy=false,systemBusy=false,sslBusy=false,previewBusy=false,retentionBusy=false;
function parsePayload(job){try{return JSON.parse(job.payload_json||'{}');}catch{return{};}}
async function processOneJob(){if(jobBusy)return;const job=jobs.claim();if(!job)return;jobBusy=true;try{const p=parsePayload(job);if(job.type==='deploy'){const app=appModel.find(p.appId,job.workspace_id);if(!app)throw new Error('Project queue target tidak ditemukan.');const result=await appService.deploy(app,{workspaceId:job.workspace_id,trigger:p.trigger||'queue'});await notifications.notify(job.workspace_id,{level:'success',type:'deploy',title:`Deploy berhasil · ${app.name}`,message:`Release ${result.releaseId||result.commit||'baru'} aktif dan health check berhasil.`,resourceType:'app',resourceId:String(app.id)});}else if(job.type==='preview_create'){const item=await previews.create(job.workspace_id,p.userId||null,p.appId,p.branch,p.ttlDays||7);await notifications.notify(job.workspace_id,{level:'success',type:'preview',title:`Preview ready · ${item.branch}`,message:item.hostname?`https://${item.hostname}`:`Preview port ${item.port}`,resourceType:'preview',resourceId:String(item.id)});}else if(job.type==='preview_remove'){const item=previews.find(p.previewId,job.workspace_id);if(item)await previews.remove(item);}else throw new Error(`Job type ${job.type} tidak didukung.`);jobs.success(job.id);}catch(error){jobs.failJob(job,error);try{await alerts.evaluateMetric(job.workspace_id,'job_failed',1,String(job.id),String(error.message||error).slice(0,1000));await notifications.notify(job.workspace_id,{level:'critical',type:'job',title:'Background job gagal',message:String(error.message||error).slice(0,1000),resourceType:'job',resourceId:String(job.id)});}catch{}}finally{jobBusy=false;}}
function recentNotification(workspaceId,type,resourceId,hours=6){return Boolean(db.prepare("SELECT 1 FROM notifications WHERE workspace_id=? AND type=? AND COALESCE(resource_id,'')=? AND datetime(created_at)>=datetime('now',?) LIMIT 1").get(workspaceId,type,String(resourceId||''),`-${hours} hours`));}
async function healthSweep(){if(healthBusy)return;healthBusy=true;try{const due=db.prepare("SELECT * FROM apps WHERE last_health_at IS NULL OR datetime(last_health_at)<=datetime('now','-' || MAX(60,health_interval_sec) || ' seconds') ORDER BY COALESCE(last_health_at,'1970-01-01') LIMIT 8").all();for(const app of due){const h=await appService.health(app);await alerts.evaluateMetric(app.workspace_id,'app_unhealthy',h.ok?0:1,String(app.id),h.ok?`${app.name} sehat.`:`${app.name} health check gagal${h.statusCode?` (HTTP ${h.statusCode})`:''}.`);const open=db.prepare("SELECT * FROM health_incidents WHERE app_id=? AND status='open' ORDER BY id DESC LIMIT 1").get(app.id);if(!h.ok&&!open){db.prepare("INSERT INTO health_incidents (app_id,status,message) VALUES (?,'open',?)").run(app.id,String(h.error||`HTTP ${h.statusCode||0}`).slice(0,500));await notifications.notify(app.workspace_id,{level:'critical',type:'health',title:`Project unhealthy · ${app.name}`,message:`Health check ${app.health_path||'/'} gagal${h.statusCode?` (HTTP ${h.statusCode})`:''}.`,resourceType:'app',resourceId:String(app.id)});}else if(h.ok&&open){db.prepare("UPDATE health_incidents SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?").run(open.id);await notifications.notify(app.workspace_id,{level:'success',type:'health',title:`Project recovered · ${app.name}`,message:`Health check kembali normal (${h.latencyMs||0} ms).`,resourceType:'app',resourceId:String(app.id)});}}}catch(error){console.error('health sweep failed:',error.message);}finally{healthBusy=false;}}
async function systemSweep(){if(systemBusy)return;systemBusy=true;try{const m=JSON.parse((await runtime.run('metrics-summary',[],{timeout:15000})).stdout||'{}');const memPct=m.memory?.total?Math.round((Number(m.memory.used||0)/Number(m.memory.total))*100):0;const diskPct=Number(m.disk?.percent||0);const load=Number(m.loadavg?.[0]||0),cpus=Math.max(1,Number(m.cpuCount||1)),loadPerCpu=load/cpus;for(const w of alerts.workspaces()){alerts.ensureDefaults(w.id);await alerts.evaluateMetric(w.id,'memory_percent',memPct,'local',`Memory usage ${memPct}%`);await alerts.evaluateMetric(w.id,'disk_percent',diskPct,'local',`Disk usage ${diskPct}%`);await alerts.evaluateMetric(w.id,'load_per_cpu',Number(loadPerCpu.toFixed(2)),'local',`Load/CPU ${loadPerCpu.toFixed(2)}`);}const legacy=[];if(diskPct>=90)legacy.push(['disk',`Disk usage ${diskPct}%`]);if(memPct>=92)legacy.push(['memory',`Memory usage ${memPct}%`]);if(loadPerCpu>=2)legacy.push(['load',`Load ${load.toFixed(2)} pada ${cpus} CPU`]);if(legacy.length){const workspaces=db.prepare("SELECT id FROM workspaces WHERE status='active'").all();for(const w of workspaces)for(const [key,msg] of legacy)if(!recentNotification(w.id,'server',key,6))await notifications.notify(w.id,{level:'warn',type:'server',title:'Server resource warning',message:msg,resourceType:'server',resourceId:key});}}catch(error){console.error('system sweep failed:',error.message);}finally{systemBusy=false;}}
function certCovers(cert,hostname){const names=Array.isArray(cert.domains)?cert.domains:[];return names.some(n=>n===hostname||(n.startsWith('*.')&&hostname.split('.').length===n.slice(2).split('.').length+1&&hostname.endsWith(`.${n.slice(2)}`)));}
async function sslSweep(){if(sslBusy)return;sslBusy=true;try{const s=JSON.parse((await runtime.run('ssl-status',[],{timeout:20000})).stdout||'{}');const certs=Array.isArray(s.certificates)?s.certificates:[];const domains=db.prepare('SELECT id,workspace_id,hostname,ssl_enabled FROM domains WHERE ssl_enabled=1').all();for(const d of domains){const cert=certs.find(c=>certCovers(c,d.hostname));if(!cert){if(!recentNotification(d.workspace_id,'ssl',d.hostname,24))await notifications.notify(d.workspace_id,{level:'critical',type:'ssl',title:`Certificate missing · ${d.hostname}`,message:'Domain ditandai HTTPS tetapi certificate yang mencakup hostname tidak ditemukan.',resourceType:'domain',resourceId:d.hostname});continue;}await alerts.evaluateMetric(d.workspace_id,'ssl_days',Number(cert.daysRemaining??999),d.hostname,`SSL ${d.hostname} tersisa ${cert.daysRemaining} hari.`);if(Number(cert.daysRemaining)<=14&&!recentNotification(d.workspace_id,'ssl',d.hostname,24)){await notifications.notify(d.workspace_id,{level:Number(cert.daysRemaining)<=7?'critical':'warn',type:'ssl',title:`SSL expires soon · ${d.hostname}`,message:`Certificate ${cert.name} tersisa ${cert.daysRemaining} hari.${cert.renewalAuto?' Auto-renew terdeteksi.':' Certificate ini tidak memiliki auto-renew.'}`,resourceType:'domain',resourceId:d.hostname});}}}catch(error){console.error('ssl sweep failed:',error.message);}finally{sslBusy=false;}}
async function previewSweep(){if(previewBusy)return;previewBusy=true;try{await previews.cleanupExpired();}catch(error){console.error('preview sweep failed:',error.message);}finally{previewBusy=false;}}
function retentionSweep(){if(retentionBusy)return;retentionBusy=true;try{db.prepare("DELETE FROM metric_samples WHERE sampled_at < datetime('now','-14 days')").run();db.prepare("DELETE FROM job_queue WHERE status='success' AND finished_at < datetime('now','-14 days')").run();db.prepare("DELETE FROM job_dead_letters WHERE failed_at < datetime('now','-90 days')").run();}catch(error){console.error('retention sweep failed:',error.message);}finally{retentionBusy=false;}}
function start(){jobs.recoverStale();const timers=[setInterval(processOneJob,4000),setInterval(healthSweep,60000),setInterval(systemSweep,300000),setInterval(sslSweep,3600000),setInterval(previewSweep,600000),setInterval(retentionSweep,3600000)];for(const t of timers)t.unref();setTimeout(processOneJob,1200).unref();setTimeout(healthSweep,5000).unref();setTimeout(systemSweep,10000).unref();setTimeout(sslSweep,15000).unref();setTimeout(previewSweep,20000).unref();setTimeout(retentionSweep,25000).unref();return()=>timers.forEach(clearInterval);}
module.exports={start,processOneJob,healthSweep,systemSweep,sslSweep,previewSweep,retentionSweep};
