'use strict';
const bcrypt=require('bcryptjs');const crypto=require('node:crypto');const nodemailer=require('nodemailer');
const model=require('./auth.model');
const {validatePassword,MAX_PASSWORD_BYTES}=require('../../lib/password-policy');
const vault=require('../../core/security/vault');
const totp=require('../../core/security/totp');const config=require('../../core/config');

async function createAdmin(emailRaw,passwordRaw){const email=String(emailRaw||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)||email.length>254)throw new Error('Gunakan alamat email yang valid.');const password=validatePassword(passwordRaw);const hash=await bcrypt.hash(password,12);const info=model.createAdmin(email,hash);return{id:Number(info.lastInsertRowid),email,role:'admin',locale:'id',totpEnabled:false};}
async function authenticate(emailRaw,passwordRaw){const email=String(emailRaw||'').trim().toLowerCase();const password=String(passwordRaw||'');if(Buffer.byteLength(password,'utf8')>MAX_PASSWORD_BYTES)return null;const user=model.findByEmail(email);if(!user||user.disabled_at||!(await bcrypt.compare(password,user.password_hash)))return null;try{if(bcrypt.getRounds(user.password_hash)<12)model.updateHash(user.id,await bcrypt.hash(password,12));}catch{}return{id:user.id,email:user.email,role:user.role,locale:user.locale||'id',totpEnabled:Boolean(user.totp_enabled)};}
function verifySecondFactor(userId,input){const user=model.findById(userId);if(!user||!user.totp_enabled||!user.totp_secret_enc)return false;let secret;try{secret=vault.decrypt(user.totp_secret_enc);}catch{return false;}if(totp.verify(secret,input))return true;let hashes=[];try{hashes=JSON.parse(vault.decrypt(user.recovery_codes_enc||''));}catch{}const fp=vault.fingerprint(String(input||'').trim().toLowerCase());const idx=hashes.indexOf(fp);if(idx<0)return false;hashes.splice(idx,1);model.update2fa(user.id,{secretEnc:user.totp_secret_enc,enabled:true,recoveryEnc:vault.encrypt(JSON.stringify(hashes))});return true;}

async function requestPasswordReset(emailRaw,baseUrl){const email=String(emailRaw||'').trim().toLowerCase();const user=model.findByEmail(email);if(!user||user.disabled_at)return{sent:true};const token=`nhpr_${crypto.randomBytes(32).toString('base64url')}`,hash=crypto.createHash('sha256').update(token).digest('hex');model.createReset(user.id,hash);const url=`${String(baseUrl||'').replace(/\/$/,'')}/reset-password/${encodeURIComponent(token)}`;if(config.smtp.host&&config.smtp.from){const transport=nodemailer.createTransport({host:config.smtp.host,port:config.smtp.port,secure:config.smtp.secure,auth:config.smtp.user?{user:config.smtp.user,pass:config.smtp.pass}:undefined,pool:false,connectionTimeout:10000,socketTimeout:10000});try{await transport.sendMail({from:config.smtp.from,to:user.email,subject:'[HostPanel] Reset password',text:`Permintaan reset password HostPanel. Link berlaku 30 menit:\n\n${url}\n\nAbaikan email ini bila bukan Anda yang meminta.`});}finally{transport.close();}}else if(config.env!=='production'){console.log(`DEV password reset: ${url}`);}return{sent:true};}
function verifyResetToken(raw){const token=String(raw||'');if(!/^nhpr_[A-Za-z0-9_-]{30,}$/.test(token))return null;return model.resetToken(crypto.createHash('sha256').update(token).digest('hex'));}
async function resetPassword(rawToken,passwordRaw){const row=verifyResetToken(rawToken);if(!row)throw new Error('Link reset tidak valid atau kedaluwarsa.');const password=validatePassword(passwordRaw),hash=await bcrypt.hash(password,12);model.useReset(row.id,row.user_id,hash);return row;}
module.exports={createAdmin,authenticate,verifySecondFactor,requestPasswordReset,verifyResetToken,resetPassword};
