'use strict';
const dns=require('node:dns').promises;const net=require('node:net');const nodemailer=require('nodemailer');const config=require('../../core/config');const vault=require('../../core/security/vault');const model=require('./notifications.model');
function isPrivateIp(ip){if(net.isIP(ip)===4){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]>=224);}if(net.isIP(ip)===6){const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe8')||v.startsWith('fe9')||v.startsWith('fea')||v.startsWith('feb');}return true;}
async function safeWebhookUrl(raw){let url;try{url=new URL(String(raw||''));}catch{throw new Error('Webhook URL tidak valid.');}if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443')throw new Error('Webhook wajib HTTPS port 443 tanpa credential di URL.');const addresses=await dns.lookup(url.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(x=>isPrivateIp(x.address)))throw new Error('Webhook tidak boleh mengarah ke loopback/private/link-local network.');return url.toString();}
function channelPayload(type,body){const name=String(body.name||'').trim().slice(0,80);if(!name)throw new Error('Nama channel wajib diisi.');if(type==='webhook')return{name,url:String(body.url||'').trim()};if(type==='telegram'){const token=String(body.bot_token||'').trim();const chatId=String(body.chat_id||'').trim();if(!/^\d{6,12}:[A-Za-z0-9_-]{20,}$/.test(token)||!/^-?\d{5,20}$/.test(chatId))throw new Error('Telegram bot token/chat id tidak valid.');return{name,botToken:token,chatId};}if(type==='email'){const to=String(body.to||'').trim();if(!/^\S+@\S+\.\S+$/.test(to))throw new Error('Email tujuan tidak valid.');return{name,to};}throw new Error('Tipe channel tidak didukung.');}
async function addChannel(workspaceId,type,body){const payload=channelPayload(type,body);if(type==='webhook')payload.url=await safeWebhookUrl(payload.url);return model.addChannel(workspaceId,type,payload.name,vault.encrypt(JSON.stringify(payload)));}
function publicChannels(workspaceId){return model.channels(workspaceId).map(c=>({id:c.id,type:c.type,name:c.name,enabled:Boolean(c.enabled),created_at:c.created_at}));}
async function sendChannel(c,n){if(!c.enabled)return;const cfg=JSON.parse(vault.decrypt(c.config_enc));const text=`[${n.level.toUpperCase()}] ${n.title}\n${n.message}`;if(c.type==='webhook'){const url=await safeWebhookUrl(cfg.url);const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','user-agent':'Nusantara-HostPanel/1.0'},body:JSON.stringify({source:'nusantara-hostpanel',...n}) ,signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Webhook HTTP ${r.status}`);return;}if(c.type==='telegram'){const r=await fetch(`https://api.telegram.org/bot${encodeURIComponent(cfg.botToken)}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:cfg.chatId,text}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Telegram HTTP ${r.status}`);return;}if(c.type==='email'){if(!config.smtp.host||!config.smtp.from)throw new Error('SMTP global belum dikonfigurasi platform admin.');const transport=nodemailer.createTransport({host:config.smtp.host,port:config.smtp.port,secure:config.smtp.secure,auth:config.smtp.user?{user:config.smtp.user,pass:config.smtp.pass}:undefined,pool:false,connectionTimeout:10000,socketTimeout:10000});await transport.sendMail({from:config.smtp.from,to:cfg.to,subject:`[HostPanel] ${n.title}`,text});transport.close();}}
async function notify(workspaceId,n,{deliver=true}={}){model.create(workspaceId,n);if(!deliver)return;const channels=model.channels(workspaceId).filter(c=>c.enabled);for(const c of channels){try{await sendChannel(c,n);}catch(error){console.error(`notification channel ${c.id} failed:`,error.message);}}}
module.exports={list:model.list,unreadCount:model.unreadCount,markRead:model.markRead,markAllRead:model.markAllRead,remove:model.remove,removeRead:model.removeRead,removeAll:model.removeAll,removeSelected:model.removeSelected,publicChannels,addChannel,toggle:model.toggle,removeChannel:model.removeChannel,notify,safeWebhookUrl};
