'use strict';
function build({permissions,dnsPublic=false,unreadNotifications=0,t=(k,f)=>f}={}){
  const p=permissions||{};const groups=[];const add=(name,links)=>{const visible=links.filter(i=>i&&i.visible!==false);if(visible.length)groups.push([name,visible.map(({href,label,icon})=>[href,label,icon])]);};
  add('Workspace',[{href:'/',label:t('nav.overview','Overview'),icon:'home'},{href:'/workspaces',label:t('nav.workspaces','Workspaces'),icon:'layers'},{href:'/team',label:t('nav.team','Team & RBAC'),icon:'users',visible:p.canWorkspaceAdmin},{href:'/billing',label:t('nav.billing','Billing & Plans'),icon:'credit-card',visible:p.canWorkspaceAdmin},{href:'/notifications',label:`${t('nav.notifications','Notifications')}${unreadNotifications?` (${unreadNotifications})`:''}`,icon:'bell'}]);
  add('Build & Ship',[{href:'/apps',label:t('nav.projects','Projects'),icon:'rocket'},{href:'/deployments',label:t('nav.deployments','Deployments'),icon:'git-branch'},{href:'/previews',label:t('nav.previews','Preview Environments'),icon:'eye',visible:p.canDevelop},{href:'/integrations',label:t('nav.integrations','Integrations'),icon:'plug',visible:p.canDevelop},{href:'/logs',label:t('nav.logs','Log Center'),icon:'terminal',visible:p.canDevelop}]);
  add('Network',[{href:'/domains',label:t('nav.domains','Domain & Nginx'),icon:'globe'},{href:'/dns',label:dnsPublic?t('nav.dns','DNS BIND9'):`${t('nav.dns','DNS BIND9')} (lokal)`,icon:'network'},{href:'/ssl',label:t('nav.ssl','SSL & Renewal'),icon:'lock',visible:p.canPlatformOperate}]);
  add('Operations',[{href:'/alerts',label:t('nav.alerts','Alerts & Rules'),icon:'triangle-alert',visible:p.canDevelop},{href:'/monitoring',label:t('nav.monitoring','Monitoring Server'),icon:'activity',visible:p.canPlatformOperate},{href:'/backups',label:t('nav.backups','Backup & Restore Server'),icon:'database-backup',visible:p.canPlatformOperate},{href:'/services',label:t('nav.services','Layanan Server'),icon:'server',visible:p.canPlatformOperate}]);
  add('Data & Security',[{href:'/database',label:t('nav.database','Database Manager'),icon:'database',visible:p.canWorkspaceAdmin},{href:'/security',label:t('nav.security','Security Center'),icon:'shield'},{href:'/settings',label:t('nav.settings','Platform Settings'),icon:'settings',visible:p.canPlatformOperate}]);
  add('Resources',[{href:'/docs',label:t('nav.docs','Documentation'),icon:'book-open'},{href:'/updates',label:t('nav.updates','Release & Updates'),icon:'refresh-cw',visible:p.canPlatformOperate}]);return groups;
}
function mobile(p={}){const links=[['/','home','Home'],['/apps','rocket','Projects']];if(p.canDevelop&&!p.suspended)links.push(['/apps/new','plus','Deploy']);links.push(p.canPlatformOperate?['/monitoring','activity','Monitor']:['/domains','globe','Domains']);return links;}
module.exports={build,mobile};
