'use strict';
const db=require('../database');

function memberships(userId){return db.prepare(`SELECT w.*,wm.role AS membership_role FROM workspace_members wm JOIN workspaces w ON w.id=wm.workspace_id WHERE wm.user_id=? ORDER BY CASE wm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'developer' THEN 2 ELSE 3 END,w.id`).all(userId);}
function workspaceFor(user,requestedId){if(!user)return null;const all=memberships(user.id);if(user.role==='admin'&&requestedId){const any=db.prepare('SELECT *,\'owner\' AS membership_role FROM workspaces WHERE id=?').get(Number(requestedId));if(any)return any;}const requested=Number(requestedId||0);return all.find((w)=>w.id===requested)||all[0]||null;}
function attach(req,res,next){if(!req.session?.user){res.locals.workspace=null;res.locals.workspaces=[];res.locals.workspaceRole=null;return next();}const all=req.session.user.role==='admin'?db.prepare("SELECT w.*,COALESCE(wm.role,'owner') AS membership_role FROM workspaces w LEFT JOIN workspace_members wm ON wm.workspace_id=w.id AND wm.user_id=? ORDER BY w.id").all(req.session.user.id):memberships(req.session.user.id);let ws=workspaceFor(req.session.user,req.session.workspaceId);if(!ws&&req.session.user.role==='admin')ws=db.prepare("SELECT *, 'owner' AS membership_role FROM workspaces ORDER BY id LIMIT 1").get()||null;if(ws)req.session.workspaceId=ws.id;req.workspace=ws;req.workspaces=all;res.locals.workspace=ws;res.locals.workspaces=all;res.locals.workspaceRole=ws?.membership_role||null;next();}
function roleRank(role){return {viewer:1,developer:2,admin:3,owner:4}[role]||0;}
function can(req,min='viewer'){if(req.session?.user?.role==='admin')return true;return roleRank(req.workspace?.membership_role)>=roleRank(min);}
function requireWorkspace(req,res,next){if(!req.session?.user)return res.redirect('/login');if(!req.workspace)return res.status(403).render('error',{title:'Workspace diperlukan',error:'Akun ini belum menjadi anggota workspace.'});next();}
function requireWorkspaceRole(min){return(req,res,next)=>{if(!req.session?.user)return res.redirect('/login');if(!req.workspace||!can(req,min))return res.status(403).render('error',{title:'Akses ditolak',error:`Role workspace ${min} atau lebih tinggi diperlukan.`});if(req.workspace.status==='suspended'&&req.session.user.role!=='admin')return res.status(423).render('error',{title:'Workspace ditangguhkan',error:'Workspace sedang suspended. Aksi perubahan dinonaktifkan sampai status workspace kembali aktif.'});next();};}
module.exports={memberships,workspaceFor,attach,can,requireWorkspace,requireWorkspaceRole,roleRank};
