'use strict';
const db=require('./database');
function enqueue(workspaceId,type,payload={},maxAttempts=4,options={}){const idempotency=options.idempotencyKey?String(options.idempotencyKey).slice(0,160):null,priority=Math.max(1,Math.min(Number(options.priority)||100,1000)),timeoutSec=Math.max(30,Math.min(Number(options.timeoutSec)||900,3600));if(idempotency){const existing=db.prepare("SELECT id FROM job_queue WHERE workspace_id IS ? AND idempotency_key=? AND status IN ('queued','running','success') ORDER BY id DESC LIMIT 1").get(workspaceId||null,idempotency);if(existing)return Number(existing.id);}return Number(db.prepare('INSERT INTO job_queue (workspace_id,type,payload_json,max_attempts,idempotency_key,priority,timeout_sec) VALUES (?,?,?,?,?,?,?)').run(workspaceId||null,String(type),JSON.stringify(payload),Math.max(1,Math.min(Number(maxAttempts)||4,10)),idempotency,priority,timeoutSec).lastInsertRowid);}
function claim(){return db.transaction(()=>{const job=db.prepare("SELECT * FROM job_queue WHERE status='queued' AND datetime(available_at)<=datetime('now') ORDER BY priority ASC,id ASC LIMIT 1").get();if(!job)return null;const changed=db.prepare("UPDATE job_queue SET status='running',locked_at=CURRENT_TIMESTAMP,attempts=attempts+1 WHERE id=? AND status='queued'").run(job.id);if(!changed.changes)return null;return db.prepare('SELECT * FROM job_queue WHERE id=?').get(job.id);})();}
function success(id){db.prepare("UPDATE job_queue SET status='success',finished_at=CURRENT_TIMESTAMP,error=NULL WHERE id=?").run(id);}
function failJob(job,error){const msg=String(error?.message||error||'job failed').slice(0,4000);if(Number(job.attempts)<Number(job.max_attempts)){const delaySec=Math.min(1800,Math.max(15,15*(2**Math.max(0,Number(job.attempts)-1))));db.prepare("UPDATE job_queue SET status='queued',available_at=datetime('now', ?),locked_at=NULL,error=? WHERE id=?").run(`+${delaySec} seconds`,msg,job.id);}else{db.transaction(()=>{db.prepare('INSERT INTO job_dead_letters (original_job_id,workspace_id,type,payload_json,attempts,error) VALUES (?,?,?,?,?,?)').run(job.id,job.workspace_id,job.type,job.payload_json,job.attempts,msg);db.prepare("UPDATE job_queue SET status='failed',finished_at=CURRENT_TIMESTAMP,error=? WHERE id=?").run(msg,job.id);})();}}
function recoverStale(){db.prepare("UPDATE job_queue SET status='queued',locked_at=NULL,available_at=CURRENT_TIMESTAMP WHERE status='running' AND datetime(locked_at)<datetime('now','-30 minutes')").run();}
function recent(workspaceId,limit=50){return db.prepare('SELECT * FROM job_queue WHERE workspace_id=? ORDER BY id DESC LIMIT ?').all(workspaceId,Math.max(1,Math.min(Number(limit)||50,100)));}
function deadLetters(workspaceId,limit=50){return db.prepare('SELECT * FROM job_dead_letters WHERE workspace_id=? ORDER BY id DESC LIMIT ?').all(workspaceId,Math.max(1,Math.min(Number(limit)||50,100)));}
module.exports={enqueue,claim,success,failJob,recoverStale,recent,deadLetters};
