'use strict';
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
const css=path.join(root,'public','css','app.css'),shellCss=path.join(root,'public','css','hostpanel-ui.css'),head=path.join(root,'src','views','partials','head.ejs'),ignore=path.join(root,'.gitignore'),input=path.join(root,'public','css','input.css'),js=path.join(root,'public','js','app.js'),sidebar=path.join(root,'src','views','partials','sidebar.ejs');
function fail(msg){console.error(`Asset check failed: ${msg}`);process.exit(1);}
if(!fs.existsSync(css))fail('public/css/app.css tidak ada');const stat=fs.statSync(css);if(stat.size<4096)fail(`app.css terlalu kecil (${stat.size} bytes)`);const body=fs.readFileSync(css,'utf8');for(const needle of ['.btn-primary','.nav-link','.card'])if(!body.includes(needle))fail(`app.css kehilangan ${needle}`);if(!body.includes('@media (min-width:1024px)')&&!body.includes('@media (width >= 64rem)'))fail('app.css kehilangan responsive lg breakpoint');for(const needle of ['.lg\\:grid-cols-3','.sm\\:grid-cols-2'])if(!body.includes(needle))fail(`app.css kehilangan responsive utility ${needle}`);
if(!fs.existsSync(shellCss)||fs.statSync(shellCss).size<1500)fail('hostpanel-ui.css tidak ada/terlalu kecil');const shell=fs.readFileSync(shellCss,'utf8');for(const needle of ['.app-sidebar','.sidebar-backdrop','.mobile-bottom-nav','.project-source','.repo-card'])if(!shell.includes(needle))fail(`hostpanel-ui.css kehilangan ${needle}`);
const h=fs.readFileSync(head,'utf8');if(!h.includes('/css/app.css?v=<%= release %>')||!h.includes('/css/hostpanel-ui.css?v=<%= release %>'))fail('head.ejs belum memakai versioned CSS utama + shell');
const gi=fs.readFileSync(ignore,'utf8');if(/^public\/css\/(?:app|hostpanel-ui)\.css$/m.test(gi))fail('production CSS masih di-ignore Git');const src=fs.readFileSync(input,'utf8');if(!src.includes('source("../../src")'))fail('Tailwind source path belum eksplisit ke src/');
const appJs=fs.readFileSync(js,'utf8');for(const needle of ['data-sidebar-backdrop','aria-expanded','Escape','overflow-hidden'])if(!appJs.includes(needle))fail(`mobile navigation JS kehilangan ${needle}`);const side=fs.readFileSync(sidebar,'utf8');if(!side.includes('id="sidebar"')||!side.includes('data-sidebar-close'))fail('sidebar accessibility/mobile controls belum lengkap');
console.log(`Asset bundle OK: app.css ${stat.size} bytes + responsive shell ${fs.statSync(shellCss).size} bytes`);
