'use strict';
const {run}=require('../../core/runtime');const config=require('../../core/config');const model=require('./ssl.model');
function targets(){const list=[];if(config.panelDomain)list.push({kind:'panel',label:'Admin Panel',domain:config.panelDomain,port:config.port});if(config.phpMyAdminDomain)list.push({kind:'phpmyadmin',label:'phpMyAdmin',domain:config.phpMyAdminDomain,port:0});return list;}
function getTarget(kind){return targets().find((x)=>x.kind===kind)||null;}
async function status(){let value=model.normalizeStatus({tlsMode:config.tlsMode});let error='';if(config.tlsMode==='local'||config.runtimeMode==='local'){try{value=model.normalizeStatus({...value,...JSON.parse((await run('ssl-status')).stdout||'{}')});}catch(e){error=e.message||'Gagal membaca status SSL.';}}return{status:value,error,targets:targets().map((x)=>({...x,certificate:model.certificateFor(value.certificates,x.domain)}))};}
function assertLocal(){if(config.tlsMode!=='local'&&config.runtimeMode!=='local')throw new Error('Aksi SSL lokal hanya tersedia pada TLS_MODE=local.');}
function assertEmail(){if(!config.certbotEmail&&config.runtimeMode!=='local')throw new Error('CERTBOT_EMAIL belum dikonfigurasi.');}
async function systemAction(kind,action){assertLocal();const target=getTarget(kind);if(!target)throw new Error('Target SSL tidak ditemukan.');if(['staging','issue'].includes(action))assertEmail();if(action==='preflight')await run('certbot-preflight',[target.domain],{timeout:30000});else if(action==='staging')await run('certbot-system-staging',[target.kind,target.domain,config.certbotEmail||'dev@example.test',target.port],{timeout:210000});else if(action==='issue')await run('certbot-system-issue',[target.kind,target.domain,config.certbotEmail||'dev@example.test',target.port],{timeout:210000});else if(action==='sync')await run('certbot-system-activate-existing',[target.kind,target.domain,target.port],{timeout:30000});else throw new Error('Aksi SSL tidak valid.');return target;}
async function autoIssue(){assertLocal();assertEmail();const results=[];for(const target of targets()){try{await run('certbot-system-issue',[target.kind,target.domain,config.certbotEmail||'dev@example.test',target.port],{timeout:210000});results.push({target,ok:true});}catch(error){results.push({target,ok:false,error:String(error.message||'').split('\n')[0]});}}return results;}
async function dryRun(){return run('certbot-dry-run',[],{timeout:240000});}
async function renew(){return run('certbot-renew',[],{timeout:240000});}
module.exports={targets,getTarget,status,systemAction,autoIssue,dryRun,renew};
