'use strict';
const crypto=require('node:crypto');const fs=require('node:fs');const model=require('./integrations.model');const vault=require('../../core/security/vault');const config=require('../../core/config');
function token(workspaceId){const c=model.get(workspaceId,'github');return c?.token_enc?vault.decrypt(c.token_enc):'';}
function timeoutSignal(ms=10000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);t.unref?.();return{signal:c.signal,clear:()=>clearTimeout(t)};}
async function github(path,{token:accessToken,method='GET',body}={}){const ctl=timeoutSignal(12000);try{const headers={'Accept':'application/vnd.github+json','User-Agent':'Nusantara-HostPanel/1.2','X-GitHub-Api-Version':'2022-11-28'};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(`https://api.github.com${path}`,{method,headers,body:body?JSON.stringify(body):undefined,signal:ctl.signal});const text=await r.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={message:text};}if(!r.ok)throw new Error(`GitHub API ${r.status}: ${data.message||'request failed'}`);return data;}finally{ctl.clear();}}
async function identify(accessToken){return github('/user',{token:accessToken});}
async function connectToken(workspaceId,userId,accessToken){const value=String(accessToken||'').trim();if(value.length<20||value.length>1024||/[\r\n\0\s]/.test(value))throw new Error('GitHub token tidak valid.');const account=await identify(value);model.upsert(workspaceId,'github',account.login,vault.encrypt(value),userId,{id:account.id,avatar_url:account.avatar_url||'',mode:'oauth_or_pat'});return account;}
function appReady(){return Boolean(config.github.appId&&config.github.appSlug&&config.github.appPrivateKeyPath&&fs.existsSync(config.github.appPrivateKeyPath));}
function b64url(value){return Buffer.from(value).toString('base64url');}
function appJwt(){if(!appReady())throw new Error('GitHub App belum dikonfigurasi.');const now=Math.floor(Date.now()/1000);const h=b64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const p=b64url(JSON.stringify({iat:now-30,exp:now+540,iss:String(config.github.appId)}));const sig=crypto.sign('RSA-SHA256',Buffer.from(`${h}.${p}`),fs.readFileSync(config.github.appPrivateKeyPath)).toString('base64url');return `${h}.${p}.${sig}`;}
async function appApi(path,{method='GET',body,token:accessToken}={}){return github(path,{method,body,token:accessToken||appJwt()});}
async function installationToken(workspaceId){const c=model.get(workspaceId,'github_app');if(!c) return '';let meta={};try{meta=JSON.parse(c.metadata_json||'{}');}catch{}if(!meta.installation_id)return'';const data=await appApi(`/app/installations/${Number(meta.installation_id)}/access_tokens`,{method:'POST',body:{}});return data.token||'';}
async function appInstallCallback(workspaceId,userId,installationId){if(!appReady())throw new Error('GitHub App belum dikonfigurasi.');const inst=await appApi(`/app/installations/${Number(installationId)}`);const login=inst.account?.login||`installation-${installationId}`;model.upsert(workspaceId,'github_app',login,'',userId,{installation_id:Number(installationId),account_type:inst.target_type||inst.account?.type||'',repository_selection:inst.repository_selection||'',html_url:inst.html_url||''});return{login,installationId:Number(installationId)};}
function appInstallUrl(req){if(!appReady())throw new Error('GitHub App belum dikonfigurasi.');req.session.githubAppInstall={createdAt:Date.now()};return `https://github.com/apps/${encodeURIComponent(config.github.appSlug)}/installations/new`;}
async function listRepos(workspaceId){let accessToken='';const app=model.get(workspaceId,'github_app');if(app)accessToken=await installationToken(workspaceId);if(!accessToken)accessToken=token(workspaceId);if(!accessToken)return[];const path=app?'/installation/repositories?per_page=100':'/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member';const data=await github(path,{token:accessToken});const repos=Array.isArray(data)?data:(data.repositories||[]);return repos.map(r=>({id:r.id,full_name:r.full_name,private:Boolean(r.private),default_branch:r.default_branch||'main',updated_at:r.updated_at,language:r.language,description:r.description||'',html_url:r.html_url,permissions:r.permissions||{}}));}
function parseRepo(raw){const value=String(raw||'').trim().replace(/^https:\/\/github\.com\//,'').replace(/\.git$/,'').replace(/^\/+|\/+$/g,'');if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(value))throw new Error('Repository GitHub tidak valid.');return value;}
async function repoToken(workspaceId){return await installationToken(workspaceId)||token(workspaceId);}
async function inspectRepo(workspaceId,raw,branch=''){const full=parseRepo(raw);const accessToken=await repoToken(workspaceId);let repo;try{repo=await github(`/repos/${full}`,{token:accessToken});}catch(error){if(accessToken)throw error;repo=await github(`/repos/${full}`);}const ref=encodeURIComponent(branch||repo.default_branch||'main');let pkg={};try{const f=await github(`/repos/${full}/contents/package.json?ref=${ref}`,{token:accessToken});if(f?.content)pkg=JSON.parse(Buffer.from(String(f.content).replace(/\s/g,''),'base64').toString('utf8'));}catch{}
const deps={...(pkg.dependencies||{}),...(pkg.devDependencies||{})};const scripts=pkg.scripts||{};let framework='Node.js',buildScript=scripts.build?'build':'',npmScript=scripts.start?'start':'start',entryFile='server.js',healthPath='/';if(deps.next){framework='Next.js';buildScript=scripts.build?'build':'';}else if(deps.nuxt){framework='Nuxt';buildScript=scripts.build?'build':'';}else if(deps['@nestjs/core']){framework='NestJS';buildScript=scripts.build?'build':'';entryFile='dist/main.js';}else if(deps.vite||deps['@vitejs/plugin-react']){framework='Vite';buildScript=scripts.build?'build':'';}else if(deps.express){framework='Express';}return{repo:`https://github.com/${full}`,fullName:full,defaultBranch:repo.default_branch||'main',branch:branch||repo.default_branch||'main',private:Boolean(repo.private),framework,installCommand:'npm ci',buildScript,startMode:'npm',npmScript,entryFile,healthPath,packageName:pkg.name||full.split('/')[1],description:repo.description||''};}
function oauthReady(){return Boolean(config.github.clientId&&config.github.clientSecret);}
function oauthStart(req){if(!oauthReady())throw new Error('GITHUB_CLIENT_ID/GITHUB_CLIENT_SECRET belum dikonfigurasi.');const state=crypto.randomBytes(24).toString('hex');req.session.githubOauth={state,createdAt:Date.now()};const callback=config.github.callbackUrl||`${req.protocol}://${req.get('host')}/integrations/github/callback`;const url=new URL('https://github.com/login/oauth/authorize');url.searchParams.set('client_id',config.github.clientId);url.searchParams.set('redirect_uri',callback);url.searchParams.set('scope',config.github.oauthScope);url.searchParams.set('state',state);return url.toString();}
async function oauthFinish(req,code,state){const pending=req.session.githubOauth;if(!pending||pending.state!==state||Date.now()-pending.createdAt>10*60*1000)throw new Error('OAuth state tidak valid/kedaluwarsa.');delete req.session.githubOauth;const callback=config.github.callbackUrl||`${req.protocol}://${req.get('host')}/integrations/github/callback`;const ctl=timeoutSignal(12000);try{const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','User-Agent':'Nusantara-HostPanel/1.2'},body:JSON.stringify({client_id:config.github.clientId,client_secret:config.github.clientSecret,code,redirect_uri:callback,state}),signal:ctl.signal});const data=await r.json();if(!r.ok||!data.access_token)throw new Error(data.error_description||data.error||'GitHub OAuth gagal.');return connectToken(req.workspace.id,req.session.user.id,data.access_token);}finally{ctl.clear();}}
function connections(workspaceId){return{oauth:model.get(workspaceId,'github'),app:model.get(workspaceId,'github_app')};}
module.exports={get:model.get,connections,connectToken,listRepos,inspectRepo,disconnect:model.remove,oauthReady,oauthStart,oauthFinish,appReady,appInstallUrl,appInstallCallback,repoToken};
