'use strict';
const db=require('../../core/database');
function plans(){return db.prepare('SELECT * FROM billing_plans ORDER BY monthly_price_cents,id').all();}
function plan(id){return db.prepare('SELECT * FROM billing_plans WHERE id=?').get(id);}
function upsertPlan(p){if(p.id)return db.prepare('UPDATE billing_plans SET code=?,name=?,monthly_price_cents=?,currency=?,max_apps=?,max_domains=?,max_databases=?,max_storage_mb=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(p.code,p.name,p.price,p.currency,p.maxApps,p.maxDomains,p.maxDatabases,p.maxStorage,p.active?1:0,p.id);return db.prepare('INSERT INTO billing_plans (code,name,monthly_price_cents,currency,max_apps,max_domains,max_databases,max_storage_mb,active) VALUES (?,?,?,?,?,?,?,?,?)').run(p.code,p.name,p.price,p.currency,p.maxApps,p.maxDomains,p.maxDatabases,p.maxStorage,p.active?1:0);}
function subscription(ws){return db.prepare(`SELECT s.*,p.code AS plan_code,p.name AS plan_name,p.monthly_price_cents,p.currency,p.max_apps,p.max_domains,p.max_databases,p.max_storage_mb FROM subscriptions s LEFT JOIN billing_plans p ON p.id=s.plan_id WHERE s.workspace_id=?`).get(ws);}
function setSubscription(ws,p){db.prepare(`INSERT INTO subscriptions (workspace_id,plan_id,status,provider,current_period_start,current_period_end,grace_ends_at,cancel_at_period_end) VALUES (?,?,?,? ,CURRENT_TIMESTAMP,datetime('now',?),?,?) ON CONFLICT(workspace_id) DO UPDATE SET plan_id=excluded.plan_id,status=excluded.status,provider=excluded.provider,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,grace_ends_at=excluded.grace_ends_at,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=CURRENT_TIMESTAMP`).run(ws,p.planId,p.status,p.provider||'manual',`+${p.periodDays} days`,p.graceEndsAt||null,p.cancelAtPeriodEnd?1:0);}
function syncWorkspace(ws,plan,status){db.prepare('UPDATE workspaces SET plan=?,status=?,max_apps=?,max_domains=?,max_databases=?,max_storage_mb=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(plan.code,status==='suspended'?'suspended':'active',plan.max_apps,plan.max_domains,plan.max_databases,plan.max_storage_mb,ws);}
function invoices(ws){return db.prepare('SELECT * FROM invoices WHERE workspace_id=? ORDER BY id DESC LIMIT 100').all(ws);}
function invoice(id,ws){return db.prepare('SELECT * FROM invoices WHERE id=? AND workspace_id=?').get(id,ws);}
function createInvoice(ws,subId,p){return db.prepare('INSERT INTO invoices (workspace_id,subscription_id,number,amount_cents,currency,status,due_at) VALUES (?,?,?,?,?,?,?)').run(ws,subId||null,p.number,p.amount,p.currency,p.status,p.dueAt||null);}
function markPaid(id,ws){return db.prepare("UPDATE invoices SET status='paid',paid_at=COALESCE(paid_at,CURRENT_TIMESTAMP) WHERE id=? AND workspace_id=?").run(id,ws);}
function workspaces(){return db.prepare('SELECT id,name,slug,plan,status FROM workspaces ORDER BY id').all();}
function createTransaction(p){return db.prepare(`INSERT INTO billing_transactions (workspace_id,plan_id,invoice_id,order_id,gross_amount,currency,snap_token,redirect_url) VALUES (?,?,?,?,?,?,?,?)`).run(p.workspaceId,p.planId,p.invoiceId||null,p.orderId,p.grossAmount,p.currency||'IDR',p.snapToken||null,p.redirectUrl||null);}
function transactions(ws,limit=100){return db.prepare('SELECT bt.*,bp.name AS plan_name FROM billing_transactions bt LEFT JOIN billing_plans bp ON bp.id=bt.plan_id WHERE bt.workspace_id=? ORDER BY bt.id DESC LIMIT ?').all(ws,Math.max(1,Math.min(Number(limit)||100,200)));}
function transaction(id,ws){return db.prepare('SELECT * FROM billing_transactions WHERE id=? AND workspace_id=?').get(id,ws);}
function transactionByOrder(orderId){return db.prepare('SELECT * FROM billing_transactions WHERE order_id=?').get(orderId);}
function updateTransaction(id,p){db.prepare(`UPDATE billing_transactions SET transaction_id=?,transaction_status=?,fraud_status=?,payment_type=?,raw_json=?,settled_at=CASE WHEN ? THEN COALESCE(settled_at,CURRENT_TIMESTAMP) ELSE settled_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(p.transactionId||null,p.status||'unknown',p.fraudStatus||null,p.paymentType||null,JSON.stringify(p.raw||{}),p.settled?1:0,id);}
function activatePaidTransaction(id){const trx=db.prepare('SELECT * FROM billing_transactions WHERE id=?').get(id);if(!trx)return;const p=plan(trx.plan_id);if(!p)return;const sub=subscription(trx.workspace_id);if(trx.invoice_id)markPaid(trx.invoice_id,trx.workspace_id);setSubscription(trx.workspace_id,{planId:p.id,status:'active',provider:'midtrans',periodDays:30,cancelAtPeriodEnd:false});syncWorkspace(trx.workspace_id,p,'active');if(sub?.id)db.prepare("UPDATE subscriptions SET provider='midtrans',updated_at=CURRENT_TIMESTAMP WHERE workspace_id=?").run(trx.workspace_id);}
function eventExists(key){return Boolean(db.prepare('SELECT 1 FROM billing_provider_events WHERE event_key=?').get(key));}
function recordProviderEvent(key,orderId,payload){db.prepare('INSERT OR IGNORE INTO billing_provider_events (provider,event_key,order_id,payload_json) VALUES (?,?,?,?)').run('midtrans',key,orderId||null,JSON.stringify(payload||{}));}
function paymentMethod(ws){return db.prepare("SELECT * FROM billing_payment_methods WHERE workspace_id=? AND provider='midtrans' AND active=1 ORDER BY id DESC LIMIT 1").get(ws);}
function storePaymentMethod(ws,type,tokenEnc,metadata){db.prepare('UPDATE billing_payment_methods SET active=0,updated_at=CURRENT_TIMESTAMP WHERE workspace_id=? AND provider=?').run(ws,'midtrans');db.prepare('INSERT INTO billing_payment_methods (workspace_id,provider,type,token_enc,metadata_json) VALUES (?,?,?,?,?)').run(ws,'midtrans',type||null,tokenEnc,JSON.stringify(metadata||{}));}
function setProviderSubscription(ws,id,status='active'){db.prepare("UPDATE subscriptions SET provider='midtrans',provider_subscription_id=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE workspace_id=?").run(id,status,ws);}
module.exports={plans,plan,upsertPlan,subscription,setSubscription,syncWorkspace,invoices,invoice,createInvoice,markPaid,workspaces,createTransaction,transactions,transaction,transactionByOrder,updateTransaction,activatePaidTransaction,eventExists,recordProviderEvent,paymentMethod,storePaymentMethod,setProviderSubscription};
