'use strict';const model=require('./billing.model');const midtrans=require('./midtrans.service');
function planPayload(body){const id=body.id?Number(body.id):null,code=String(body.code||'').trim().toLowerCase();if(!/^[a-z0-9][a-z0-9-]{1,31}$/.test(code))throw new Error('Plan code tidak valid.');const name=String(body.name||'').trim().slice(0,80);if(!name)throw new Error('Nama plan wajib.');const n=(k,max=1e9)=>{const v=Math.max(0,Math.min(Number(body[k])||0,max));return Math.floor(v);};return{id,code,name,price:n('monthly_price_cents'),currency:String(body.currency||'IDR').toUpperCase().slice(0,3),maxApps:n('max_apps',10000),maxDomains:n('max_domains',100000),maxDatabases:n('max_databases',10000),maxStorage:n('max_storage_mb',100000000),active:String(body.active||'1')!=='0'};}
function setSubscription(ws,body){const plan=model.plan(Number(body.plan_id));if(!plan)throw new Error('Plan tidak ditemukan.');const status=['trialing','active','past_due','grace','suspended','cancelled'].includes(String(body.status))?String(body.status):'active';const periodDays=Math.max(1,Math.min(Number(body.period_days)||30,366));model.setSubscription(ws,{planId:plan.id,status,provider:'manual',periodDays,cancelAtPeriodEnd:Boolean(body.cancel_at_period_end)});model.syncWorkspace(ws,plan,status);}
function createInvoice(ws,body){const sub=model.subscription(ws),amount=Math.max(0,Math.floor(Number(body.amount_cents)||0)),currency=String(body.currency||sub?.currency||'IDR').toUpperCase().slice(0,3),number=String(body.number||`INV-${Date.now()}`).trim().slice(0,64);if(!/^[A-Za-z0-9._-]{3,64}$/.test(number))throw new Error('Nomor invoice tidak valid.');return model.createInvoice(ws,sub?.id,{number,amount,currency,status:'open',dueAt:body.due_at||null});}
async function checkout(workspace,user,planId){const p=model.plan(Number(planId));if(!p||!p.active)throw new Error('Plan tidak tersedia.');if(String(p.currency)!=='IDR')throw new Error('Midtrans checkout saat ini hanya menerima plan IDR.');const sub=model.subscription(workspace.id);const inv=model.createInvoice(workspace.id,sub?.id,{number:`INV-${workspace.id}-${Date.now()}`,amount:p.monthly_price_cents,currency:'IDR',status:'open',dueAt:null});const invoiceId=Number(inv.lastInsertRowid);return midtrans.createSnap({workspace,plan:p,user,invoiceId});}
async function startRecurring(workspace,user){return midtrans.createRecurring(workspace.id,user);}
async function setRecurring(workspaceId,enabled){return midtrans.setRecurringEnabled(workspaceId,enabled);}
async function cancel(workspaceId,id){const trx=model.transaction(Number(id),workspaceId);if(!trx)throw new Error('Transaction tidak ditemukan.');return midtrans.cancel(trx.order_id);}
async function refund(workspaceId,id,reason){const trx=model.transaction(Number(id),workspaceId);if(!trx)throw new Error('Transaction tidak ditemukan.');return midtrans.refund(trx.order_id,reason);}
async function reconcile(workspaceId,id){const trx=model.transaction(Number(id),workspaceId);if(!trx)throw new Error('Transaction tidak ditemukan.');return midtrans.reconcile(trx.order_id);}
module.exports={plans:model.plans,subscription:model.subscription,invoices:model.invoices,transactions:model.transactions,workspaces:model.workspaces,upsertPlan:(b)=>model.upsertPlan(planPayload(b)),setSubscription,createInvoice,markPaid:model.markPaid,checkout,reconcile,cancel,refund,startRecurring,setRecurring,midtransReady:midtrans.ready};
