'use strict';
const crypto=require('node:crypto');const config=require('../../core/config');const model=require('./billing.model');const vault=require('../../core/security/vault');
function ready(){return config.midtrans.enabled;}
function urls(){const prod=config.midtrans.environment==='production';return{snap:prod?'https://app.midtrans.com':'https://app.sandbox.midtrans.com',api:prod?'https://api.midtrans.com':'https://api.sandbox.midtrans.com'};}
function auth(){return `Basic ${Buffer.from(`${config.midtrans.serverKey}:`).toString('base64')}`;}
async function request(url,{method='GET',body}={}){if(!ready())throw new Error('Midtrans belum dikonfigurasi.');const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),15000);t.unref?.();try{const r=await fetch(url,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:auth(),'User-Agent':'Nusantara-HostPanel/1.2'},body:body?JSON.stringify(body):undefined,signal:ctl.signal});const text=await r.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={status_message:text};}if(!r.ok)throw new Error(`Midtrans HTTP ${r.status}: ${data.status_message||data.message||'request failed'}`);return data;}finally{clearTimeout(t);}}
function orderId(workspaceId,planId){return `NHP-${workspaceId}-${planId}-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`.slice(0,50);}
async function createSnap({workspace,plan,user,invoiceId}){if(!plan||Number(plan.monthly_price_cents)<=0)throw new Error('Plan ini tidak memiliki harga checkout.');const order_id=orderId(workspace.id,plan.id);const gross_amount=Math.max(1,Math.round(Number(plan.monthly_price_cents)/100));const base=String(process.env.PANEL_PUBLIC_URL||'').replace(/\/$/,'');const payload={transaction_details:{order_id,gross_amount},customer_details:{first_name:String(user.display_name||user.email||'Customer').slice(0,255),email:user.email},item_details:[{id:`plan-${plan.code}`,price:gross_amount,quantity:1,name:String(plan.name).slice(0,50)}],...(config.midtrans.recurring?{recurring:{required:true,interval_unit:'month'}}:{}),...(base?{callbacks:{finish:`${base}/billing?payment=finish`,error:`${base}/billing?payment=error`,pending:`${base}/billing?payment=pending`}}:{})};const data=await request(`${urls().snap}/snap/v1/transactions`,{method:'POST',body:payload});model.createTransaction({workspaceId:workspace.id,planId:plan.id,invoiceId,orderId:order_id,grossAmount:gross_amount,currency:'IDR',snapToken:data.token||null,redirectUrl:data.redirect_url||null});return{...data,order_id};}
function signature(body){return crypto.createHash('sha512').update(`${body.order_id||''}${body.status_code||''}${body.gross_amount||''}${config.midtrans.serverKey}`).digest('hex');}
function verifyNotification(body){if(!ready())return false;const expected=signature(body);const actual=String(body.signature_key||'');if(expected.length!==actual.length)return false;try{return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(actual));}catch{return false;}}
async function status(orderId){return request(`${urls().api}/v2/${encodeURIComponent(orderId)}/status`);}
function normalizedStatus(data){const s=String(data.transaction_status||'').toLowerCase();const fraud=String(data.fraud_status||'').toLowerCase();if((s==='settlement'||s==='capture')&&(!fraud||fraud==='accept'))return'paid';if(['deny','cancel','expire','failure'].includes(s))return'failed';if(['pending','authorize'].includes(s))return'pending';if(['refund','partial_refund'].includes(s))return'refunded';return s||'unknown';}
async function recurringCredential(remote,body){const paymentType=String(remote.payment_type||body.payment_type||'');const accountId=String(remote.account_id||body.account_id||'');let token=String(remote.saved_token_id||body.saved_token_id||'');if(!token&&paymentType==='gopay'&&accountId){try{const account=await request(`${urls().api}/v2/pay/account/${encodeURIComponent(accountId)}`);const options=Array.isArray(account?.metadata?.payment_options)?account.metadata.payment_options:[];const active=options.find((item)=>item&&item.active&&item.token)||options.find((item)=>item&&item.token);token=String(active?.token||'');}catch{/* Checkout tetap sah walau token recurring belum tersedia. */}}return{paymentType,accountId,token};}
async function processNotification(body){if(!verifyNotification(body))throw Object.assign(new Error('Midtrans signature tidak valid.'),{status:401});const eventKey=crypto.createHash('sha256').update(JSON.stringify([body.order_id,body.transaction_id,body.transaction_status,body.status_code,body.gross_amount])).digest('hex');if(model.eventExists(eventKey))return{duplicate:true};const remote=await status(body.order_id);const trx=model.transactionByOrder(body.order_id);if(!trx)throw Object.assign(new Error('Order Midtrans tidak dikenal.'),{status:404});if(Number(remote.gross_amount)!==Number(trx.gross_amount))throw new Error('Nominal Midtrans tidak sesuai invoice HostPanel.');const state=normalizedStatus(remote);model.recordProviderEvent(eventKey,body.order_id,body);model.updateTransaction(trx.id,{transactionId:remote.transaction_id||body.transaction_id||null,status:remote.transaction_status||body.transaction_status||'unknown',fraudStatus:remote.fraud_status||body.fraud_status||null,paymentType:remote.payment_type||body.payment_type||null,raw:remote,settled:state==='paid'});if(state==='paid')model.activatePaidTransaction(trx.id);const credential=await recurringCredential(remote,body);if(credential.token)model.storePaymentMethod(trx.workspace_id,credential.paymentType||'recurring',vault.encrypt(credential.token),{masked_card:remote.masked_card||body.masked_card||'',bank:remote.bank||body.bank||'',account_id:credential.accountId});return{duplicate:false,state,transaction:model.transactionByOrder(body.order_id)};}
async function reconcile(orderId){const remote=await status(orderId);const trx=model.transactionByOrder(orderId);if(!trx)throw new Error('Transaction tidak ditemukan.');const state=normalizedStatus(remote);model.updateTransaction(trx.id,{transactionId:remote.transaction_id||null,status:remote.transaction_status||'unknown',fraudStatus:remote.fraud_status||null,paymentType:remote.payment_type||null,raw:remote,settled:state==='paid'});if(state==='paid')model.activatePaidTransaction(trx.id);return{state,remote};}

async function createRecurring(workspaceId,user){if(!config.midtrans.recurring)throw new Error('MIDTRANS_RECURRING belum diaktifkan.');const sub=model.subscription(workspaceId);if(!sub?.plan_id)throw new Error('Subscription plan belum aktif.');const pm=model.paymentMethod(workspaceId);if(!pm)throw new Error('Token pembayaran recurring belum tersedia. Lakukan checkout recurring pertama terlebih dahulu.');const meta=JSON.parse(pm.metadata_json||'{}');const paymentType=String(pm.type||'');if(!['credit_card','gopay'].includes(paymentType))throw new Error('Metode pembayaran ini belum didukung Subscription API Midtrans.');const token=vault.decrypt(pm.token_enc);const amount=String(Math.max(1,Math.round(Number(sub.monthly_price_cents||0)/100)));const payload={name:`NHP_${workspaceId}_${sub.plan_code||'PLAN'}`.slice(0,40),amount,currency:'IDR',payment_type:paymentType,token,schedule:{interval:1,interval_unit:'month'},retry_schedule:{interval:1,interval_unit:'day',max_interval:3},metadata:{workspace_id:workspaceId,plan:sub.plan_code||''},customer_details:{first_name:String(user.display_name||user.email||'Customer').slice(0,255),email:user.email}};if(paymentType==='gopay'&&meta.account_id)payload.gopay={account_id:meta.account_id};const data=await request(`${urls().api}/v1/subscriptions`,{method:'POST',body:payload});if(!data.id)throw new Error('Midtrans tidak mengembalikan subscription id.');model.setProviderSubscription(workspaceId,data.id,'active');return data;}
async function setRecurringEnabled(workspaceId,enabled){const sub=model.subscription(workspaceId);if(!sub?.provider_subscription_id)throw new Error('Subscription Midtrans belum ada.');const data=await request(`${urls().api}/v1/subscriptions/${encodeURIComponent(sub.provider_subscription_id)}/${enabled?'enable':'disable'}`,{method:'POST'});model.setProviderSubscription(workspaceId,sub.provider_subscription_id,enabled?'active':'cancelled');return data;}


async function cancel(orderId){const data=await request(`${urls().api}/v2/${encodeURIComponent(orderId)}/cancel`,{method:'POST'});await reconcile(orderId);return data;}
async function refund(orderId,reason='HostPanel refund'){const data=await request(`${urls().api}/v2/${encodeURIComponent(orderId)}/refund`,{method:'POST',body:{reason:String(reason||'HostPanel refund').slice(0,255)}});await reconcile(orderId);return data;}

module.exports={ready,urls,createSnap,verifyNotification,processNotification,reconcile,status,normalizedStatus,createRecurring,setRecurringEnabled,cancel,refund};
